# https://www.netlify.com/blog/how-to-deploy-vue-3-and-vite-app-in-5-minutes/

[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
